# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.0-node-browsers

    working_directory: 
    #~/repo

    steps:
      - checkout

  ## Customize dependencies
dependencies:
  pre:
    - gem uninstall bundler 
    - gem install bundler --pre

  override:
    - bundle install: # note ':' here
        timeout: 180
      # run tests!
    - run:
        name: SOS Script
        command: |
          mkdir /tmp/test-results
          #TEST_FILES="$(circleci tests "/sos.rb")"
          ruby sos.rb
            
      # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results
