# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.0-node-browsers

    working_directory: 
    #~/repo

    steps:
      - checkout
      - run:
        command: gem uninstall bundler 
      - run:
        command: gem install bundler --pre
      - run:
        command: bundle install: # note ':' here
          timeout: 180
        
      - run:
        name: SOS Script
        command: |
          mkdir /tmp/test-results
          echo #PATH
          #TEST_FILES="$(circleci tests "/sos.rb")"
          ruby sos.rb
          bundle exec TEST_FILES
            
  # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
