# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.0-node-browsers

    working_directory: 
    #~/repo

    steps:
      - checkout
      - restore_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            echo $HOME
            gem install bundler
            echo $CIRCLE_WORKING_DIRECTORY
            #bundle config --local frozen true
            #bundle config --local without production:development:staging
            #bundle config --local path vendor/bundle
            bundle check || bundle install --jobs=4 --retry=3
      - run:
          name: SOS Script
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
            #TEST_FILES="$(circleci tests "/sos.rb")"
            bundle exec TEST_FILES
            ruby sos.rb
            mkdir /tmp/test-results
            
  # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
