# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.0-node-browsers
      

    working_directory: 
    #~/repo

    steps:
      - checkout

      #- run:
      #    name: install dependencies
      #    command: |
      #      bundle install --jobs=4 --retry=3 --path vendor/bundle

      ## Customize dependencies
      #dependencies:
      # pre:
        #- npm install coffeescript # install from a different package manager
        - gem install nokogiri --pre # use a custom version of bundler
        #- gem install bundler --pre
      #  - gem uninstall bundler # use a custom version of bundler
      #  - gem install bundler --pre
      #- bundle update
      #- bundle exec ruby
      # run tests!
      - run:
          name: SOS Script
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests "/sos.rb")"
            echo $CIRCLE_WORKING_DIRECTORY
            ruby sos.rb
            
      #      bundle exec rspec --format progress \
      #                      --format RspecJunitFormatter \
      #                      --out /tmp/test-results/rspec.xml \
      #                      --format progress \
      #                      $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
